CREATE DATABASE railwaydb;
USE railwaydb;

CREATE TABLE TRAIN
(TRAIN_NO VARCHAR(15) PRIMARY KEY,
EXPRESS_NAME VARCHAR(20),
FC_SEATS INT,
SC_SEATS INT,
FC_PRICE INT,
SC_PRICE INT);

CREATE TABLE EXPRESS
(EXPRESS_NO INT NOT NULL AUTO_INCREMENT PRIMARY KEY ,
TRAIN_NO VARCHAR(15),
FROMM VARCHAR(20),
TOO VARCHAR(20),
STARTING_TIME TIMESTAMP,
ARRIVAL_TIME TIMESTAMP,
FC_SEATS_REMAINING INT,
SC_SEATS_REMAINING INT,
FOREIGN KEY (TRAIN_NO) REFERENCES TRAIN(TRAIN_NO)
);

ALTER TABLE EXPRESS AUTO_INCREMENT = 10001;

CREATE TABLE USER_DETAILS
(USER_ID VARCHAR(15) PRIMARY KEY,
USERNAME VARCHAR(20),
EMAIL_ID VARCHAR(25),
PASSWORD VARCHAR(25)
);

CREATE TABLE BOOKING
(BOOKING_ID INT NOT NULL AUTO_INCREMENT PRIMARY KEY ,
EXPRESS_NO INT,
USER_ID VARCHAR(20),
TRAIN_NO VARCHAR(15),
TOTAL_FC_SEATS INT,
TOTAL_SC_SEATS INT,
TOTAL_COST INT,
FOREIGN KEY (EXPRESS_NO) REFERENCES EXPRESS(EXPRESS_NO),
FOREIGN KEY (USER_ID) REFERENCES USER_DETAILS(USER_ID),
FOREIGN KEY (TRAIN_NO) REFERENCES TRAIN(TRAIN_NO)
);