DELIMITER $$
CREATE TRIGGER bookingtrigger
AFTER INSERT ON BOOKING FOR EACH ROW
BEGIN
  UPDATE EXPRESS SET FC_SEATS_REMAINING = FC_SEATS_REMAINING - NEW.TOTAL_FC_SEATS WHERE EXPRESS_NO = NEW.EXPRESS_NO;
  UPDATE EXPRESS SET SC_SEATS_REMAINING = SC_SEATS_REMAINING - NEW.TOTAL_SC_SEATS WHERE EXPRESS_NO = NEW.EXPRESS_NO;
END$$
DELIMITER ;

DELIMITER $$
CREATE TRIGGER canceltrigger
AFTER DELETE ON BOOKING FOR EACH ROW
BEGIN
  UPDATE EXPRESS SET FC_SEATS_REMAINING = FC_SEATS_REMAINING + OLD.TOTAL_FC_SEATS WHERE EXPRESS_NO = OLD.EXPRESS_NO;
  UPDATE EXPRESS SET SC_SEATS_REMAINING = SC_SEATS_REMAINING + OLD.TOTAL_SC_SEATS WHERE EXPRESS_NO = OLD.EXPRESS_NO;
END$$
DELIMITER ;
